/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;

import br.com.marcio.padaria.front.funcoes.TeclasPermitidas;
import br.com.marcio.padaria.model.Principal;
import br.com.marcio.padaria.repositorio.Imp.PrincipalImp;
import br.com.marcio.padaria.repositorio.model.Exception.PrincipalException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Marcio
 */
public class jTela_Principal extends javax.swing.JFrame {
    
    /*
        Objetos Publicos
    */
       private final DefaultListModel lista = new DefaultListModel();
       
    /**
     * Creates new form jTela_Principal
     */
    private static jTela_Principal instance = null;
    private jTela_Principal() {
        initComponents();
        jText_valor.setDocument(new TeclasPermitidas());
        jText_valor.grabFocus();
        setAcessibilidade();
    }
    
                PrincipalImp pimp = new PrincipalImp();
		Principal principal = new Principal();
                SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");  
		SimpleDateFormat hora = new SimpleDateFormat("HH:mm");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAbrirCaixa = new javax.swing.JButton();
        jButtonFecharCaixa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jText_valor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonListaDeItens = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_vendas = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jButtonAbrirCorrecao = new javax.swing.JButton();
        jButtonAbrirClientes = new javax.swing.JButton();
        jButtonAbrirRetiradas = new javax.swing.JButton();
        jButtonAbrirDespesas = new javax.swing.JButton();
        jButtonAbrirRelatorio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAplicativos = new javax.swing.JMenu();
        jMenuItemCalculadora = new javax.swing.JMenuItem();
        jMenuInformacoes = new javax.swing.JMenu();
        jMenuItemAtalhos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PDV");
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1050, 680));
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setName("Tela Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1050, 680));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jButtonAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Caixa.png"))); // NOI18N
        jButtonAbrirCaixa.setMnemonic('a');
        jButtonAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCaixaActionPerformed(evt);
            }
        });

        jButtonFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        jButtonFecharCaixa.setMnemonic('x');
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });

        jText_valor.setBackground(new java.awt.Color(255, 255, 204));
        jText_valor.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        jText_valor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_valor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jText_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_valorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        jLabel1.setText("R$");

        jButtonListaDeItens.setMnemonic('l');
        jButtonListaDeItens.setText("Lista de compra");
        jButtonListaDeItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaDeItensActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('p');
        jButton1.setText("Consulta de preço");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAdicionar.setMnemonic('i');
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonListaDeItens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jText_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListaDeItens)
                    .addComponent(jButton1)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonLimpar))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jList_vendas);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButtonAbrirCorrecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Correca.png"))); // NOI18N
        jButtonAbrirCorrecao.setMnemonic('o');
        jButtonAbrirCorrecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCorrecaoActionPerformed(evt);
            }
        });

        jButtonAbrirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clientes.png"))); // NOI18N
        jButtonAbrirClientes.setMnemonic('c');
        jButtonAbrirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirClientesActionPerformed(evt);
            }
        });

        jButtonAbrirRetiradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Retiradas.png"))); // NOI18N
        jButtonAbrirRetiradas.setMnemonic('e');
        jButtonAbrirRetiradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirRetiradasActionPerformed(evt);
            }
        });

        jButtonAbrirDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Despesas.png"))); // NOI18N
        jButtonAbrirDespesas.setMnemonic('d');
        jButtonAbrirDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirDespesasActionPerformed(evt);
            }
        });

        jButtonAbrirRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio_1.png"))); // NOI18N
        jButtonAbrirRelatorio.setMnemonic('r');
        jButtonAbrirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirRelatorioActionPerformed(evt);
            }
        });

        jLabel4.setText("Clientes");

        jLabel5.setText("Relatórios");

        jLabel6.setText("Retiradas");

        jLabel7.setText("Correção");

        jLabel8.setText("Despesas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButtonAbrirClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrirRetiradas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrirCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrirDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel4)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAbrirDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAbrirClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbrirRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAbrirRetiradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAbrirCorrecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9))
        );

        jLabel2.setText("Abrir caixa");

        jLabel3.setText("Fechar Caixa");

        jMenuArquivo.setText("Arquivo");

        jMenuItemUsuarios.setText("Usuários");
        jMenuArquivo.add(jMenuItemUsuarios);

        jMenuItemCadastroProduto.setText("Cadastrar produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemCadastroProduto);

        jMenuItemSair.setText("Sair");
        jMenuArquivo.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenuArquivo);

        jMenuAplicativos.setText("Aplicativos");

        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });
        jMenuAplicativos.add(jMenuItemCalculadora);

        jMenuBarPrincipal.add(jMenuAplicativos);

        jMenuInformacoes.setText("Informações");

        jMenuItemAtalhos.setText("Ajuda");
        jMenuItemAtalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtalhosActionPerformed(evt);
            }
        });
        jMenuInformacoes.add(jMenuItemAtalhos);

        jMenuBarPrincipal.add(jMenuInformacoes);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListaDeItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaDeItensActionPerformed
       jTela_ListaCompra listaDeCompras = new jTela_ListaCompra();
       listaDeCompras.setModal(true);
       listaDeCompras.setVisible(true);
       String valor = String.valueOf(listaDeCompras.getValorFinal());
       jText_valor.setText(valor);
    }//GEN-LAST:event_jButtonListaDeItensActionPerformed

    private void jText_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_valorKeyPressed
  
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)  {
        String valor = (jText_valor.getText()).replace(",", ".");
        principal.setValor(valor);
        principal.setData(data.format(new Date()));
        principal.setHora(hora.format(new Date()));
           try {
               pimp.validaPrincipal(principal);
               pimp.inserir(principal);
               lista.addElement(jText_valor.getText());
               jList_vendas.setModel(lista);
               jList_vendas.ensureIndexIsVisible(lista.getSize() -1);
           } catch (PrincipalException e) {
               JOptionPane.showMessageDialog(null,e.getMessage());
           }
           jText_valor.setText("");
        }    
        
       
    }//GEN-LAST:event_jText_valorKeyPressed

    private void jButtonAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCaixaActionPerformed
       jTela_AbrirCaixa abrirCaixa = new jTela_AbrirCaixa();
       abrirCaixa.setModal(true);
       abrirCaixa.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirCaixaActionPerformed

    private void jButtonAbrirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirRelatorioActionPerformed
      jTela_Relatorio.getInstance().setVisible(true);
    }//GEN-LAST:event_jButtonAbrirRelatorioActionPerformed

    private void jButtonAbrirRetiradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirRetiradasActionPerformed
       jTela_Retiradas telaRetiradas = new jTela_Retiradas();
       telaRetiradas.setModal(true);
       telaRetiradas.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirRetiradasActionPerformed

    private void jButtonAbrirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirClientesActionPerformed
       jTela_Clientes telaClientes = new jTela_Clientes();
       telaClientes.setModal(true);
       telaClientes.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirClientesActionPerformed

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed
       jTela_Fechamento telaFechamento = new jTela_Fechamento();
       telaFechamento.setModal(true);
       telaFechamento.setVisible(true);
    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed

    private void jButtonAbrirDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirDespesasActionPerformed
       jTela_Despesas telaFechamento = new jTela_Despesas();
       telaFechamento.setModal(true);
       telaFechamento.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirDespesasActionPerformed

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed
           try {
               Runtime.getRuntime().exec( "calc" );
           } catch (IOException ex) {
               Logger.getLogger(jTela_Principal.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
       jTela_ProdutosCodBar telaProdutosCodBar = new jTela_ProdutosCodBar();
       telaProdutosCodBar.setModal(true);
       telaProdutosCodBar.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jButtonAbrirCorrecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCorrecaoActionPerformed
       jTela_Correcao telaCorrecao = new jTela_Correcao();
       telaCorrecao.setModal(true);
       telaCorrecao.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirCorrecaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTela_ConsultarPreco telaConsultarPreco = new jTela_ConsultarPreco();
        telaConsultarPreco.setModal(true);
        telaConsultarPreco.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        String valor = (jText_valor.getText()).replace(",", ".");
        principal.setValor(valor);
        principal.setData(data.format(new Date()));
        principal.setHora(hora.format(new Date()));
           try {
               pimp.validaPrincipal(principal);
               pimp.inserir(principal);
               lista.addElement(jText_valor.getText());
               jList_vendas.setModel(lista);
               jList_vendas.ensureIndexIsVisible(lista.getSize() -1);
           } catch (PrincipalException e) {
               JOptionPane.showMessageDialog(null,e.getMessage());
           }
           jText_valor.setText("");
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jMenuItemAtalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtalhosActionPerformed
        jTela_Ajuda abrirAjuda = new jTela_Ajuda();
       abrirAjuda.setModal(true);
       abrirAjuda.setVisible(true);
    }//GEN-LAST:event_jMenuItemAtalhosActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jText_valor.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed


    public static void main(String args[]) throws Exception {
       try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_Principal().setVisible(true);
            }
        });
    }
    
    /*Função de acessibilidade*/
     private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
     
     public static jTela_Principal getInstance(){
        if (instance == null){
            instance = new jTela_Principal();
        } 
     return instance;
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAbrirCaixa;
    private javax.swing.JButton jButtonAbrirClientes;
    private javax.swing.JButton jButtonAbrirCorrecao;
    private javax.swing.JButton jButtonAbrirDespesas;
    private javax.swing.JButton jButtonAbrirRelatorio;
    private javax.swing.JButton jButtonAbrirRetiradas;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonListaDeItens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList_vendas;
    private javax.swing.JMenu jMenuAplicativos;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuInformacoes;
    private javax.swing.JMenuItem jMenuItemAtalhos;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText_valor;
    // End of variables declaration//GEN-END:variables
}
