/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;

import br.com.marcio.padaria.front.funcoes.TeclasPermitidas;
import br.com.marcio.padaria.model.Pendencias;
import br.com.marcio.padaria.repositorio.Imp.PendenciasImp;
import br.com.marcio.padaria.repositorio.model.Exception.PendenciasException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MgSouza
 */
public class jTela_Pagamento extends javax.swing.JDialog {
    private String cd_cliente;
    private Double valor_maximo;
    /**
     * Creates new form jTela_Pagamento
     */
    private static jTela_Pagamento instance = null;
    public jTela_Pagamento() {
        initComponents();
        jTextFieldValor.setDocument(new TeclasPermitidas());
        setAcessibilidade();
    }
    
    public jTela_Pagamento(String cd_cliente, Double valor_maximo){
        this.cd_cliente = cd_cliente;
        this.valor_maximo = valor_maximo;
        initComponents();
        jTextFieldValor.setDocument(new TeclasPermitidas());
        setAcessibilidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPagar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");
        setMaximumSize(new java.awt.Dimension(176, 92));
        setMinimumSize(new java.awt.Dimension(176, 92));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPagar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        double valor = Double.parseDouble(jTextFieldValor.getText().replace(",","."));
        if (valor > valor_maximo){
            JOptionPane.showMessageDialog(null, "Valor acima do limite de pagamento - " +
                    valor_maximo, "Erro", JOptionPane.INFORMATION_MESSAGE);
        } else {
           valor = valor * -1;
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");  
	SimpleDateFormat hora = new SimpleDateFormat("HH:mm");

        PendenciasImp pimp = new PendenciasImp();
        Pendencias pendencia = new Pendencias();
        
        pendencia.setCd_cliente(Integer.parseInt(cd_cliente));
        pendencia.setData(data.format(new Date()));
        pendencia.setValor(String.valueOf(valor));
        pendencia.setDescricao("Pagamento");
        pendencia.setHora(hora.format(new Date()));
       
        
        try {
            pimp.validaPendencia(pendencia);
            pimp.inserir(pendencia);
            this.dispose();
        } catch (PendenciasException ex) {
           JOptionPane.showMessageDialog(null, "Não foi possível gravar dados!", "Erro", JOptionPane.ERROR_MESSAGE);
            
        }
        }
        
        
        
        
        //Concluir tela de pagamento
    }//GEN-LAST:event_jButtonPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Pagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jTela_Pagamento().setVisible(true);
            }
        });
    }
    
    private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
    
    public static jTela_Pagamento getInstance(){
        if (instance == null) {
            instance = new jTela_Pagamento();
        }
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
