/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;

import br.com.marcio.padaria.front.funcoes.TableModelDespesas;
import br.com.marcio.padaria.front.funcoes.TableModelPrincipal;
import br.com.marcio.padaria.front.funcoes.TableModelRetiradas;
import br.com.marcio.padaria.model.Despesas;
import br.com.marcio.padaria.model.Principal;
import br.com.marcio.padaria.model.Retiradas;
import br.com.marcio.padaria.repositorio.Imp.DespesasImp;
import br.com.marcio.padaria.repositorio.Imp.PrincipalImp;
import br.com.marcio.padaria.repositorio.Imp.RetiradasImp;
import br.com.marcio.padaria.repositorio.model.Exception.DespesasException;
import br.com.marcio.padaria.repositorio.model.Exception.PrincipalException;
import br.com.marcio.padaria.repositorio.model.Exception.RetiradasException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MgSouza
 */
public class jTela_Correcao extends javax.swing.JDialog {
    
    /**
     * Creates new form jTela_Correcao
     */
    private static jTela_Correcao instance = null;
    public jTela_Correcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCorrecao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonRetiradas = new javax.swing.JRadioButton();
        jRadioButtonDespesas = new javax.swing.JRadioButton();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtonPDV = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorrecao = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Correção");
        setMaximumSize(new java.awt.Dimension(450, 380));
        setMinimumSize(new java.awt.Dimension(366, 380));
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de correção"));

        buttonGroupCorrecao.add(jRadioButtonRetiradas);
        jRadioButtonRetiradas.setSelected(true);
        jRadioButtonRetiradas.setText("Retiradas");

        buttonGroupCorrecao.add(jRadioButtonDespesas);
        jRadioButtonDespesas.setText("Despesas");

        jButtonPesquisar.setMnemonic('p');
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        buttonGroupCorrecao.add(jRadioButtonPDV);
        jRadioButtonPDV.setText("PDV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonRetiradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisar)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRetiradas)
                    .addComponent(jRadioButtonDespesas)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jRadioButtonPDV))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableCorrecao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCorrecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCorrecaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCorrecao);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
      if (jRadioButtonDespesas.isSelected()){
          consultaDespesas();
      } else if (jRadioButtonRetiradas.isSelected()) {
          consultaRetiradas();
      } else if (jRadioButtonPDV.isSelected()){
          consultaPDV();
      }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTableCorrecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCorrecaoMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {   
             int lin = jTableCorrecao.getSelectedRow();
             //System.out.println(jTableCorrecao.getValueAt(lin, 0));
             int pk_correcao = (int)jTableCorrecao.getValueAt(lin, 0);
            
             if (jRadioButtonDespesas.isSelected()) {
               
                Despesas despesa = new Despesas();
                despesa.setCd_despesa(pk_correcao);
                //despesa.setData("");
                despesa.setDescricao((String)jTableCorrecao.getValueAt(lin, 3));
               
                jInputBox telaInput = new jInputBox("Digite o novo valor para despesa:","despesa", despesa);
                telaInput.setModal(true);
                telaInput.setVisible(true);
                consultaDespesas();
                
             
            }  else if (jRadioButtonRetiradas.isSelected()){
             
                Retiradas retirada = new Retiradas();
                retirada.setCd_retiradas(pk_correcao);
                jInputBox telaInput = new jInputBox("Digite o novo valor para retirada:","retirada", retirada);
                telaInput.setModal(true);
                telaInput.setVisible(true);
                consultaRetiradas();
                             

            } else if (jRadioButtonPDV.isSelected()){
                 Principal principal = new Principal();
                 principal.setCd_principal(pk_correcao);
                 jInputBox telaInput = new jInputBox("Digite o novo valor para entrada:","PDV", principal);
                 telaInput.setModal(true);
                 telaInput.setVisible(true);
                 consultaPDV();
            }
            
            
        }
    }//GEN-LAST:event_jTableCorrecaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
          
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Correcao.class.getName()).log(Level.SEVERE, null, ex);
        }
                
               
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_Correcao().setVisible(true);
            }
        });
    }
    private void consultaRetiradas(){
        RetiradasImp rimp = new RetiradasImp();
			SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy"); 
			ArrayList<Retiradas> lista;
			Retiradas retirada;
			try {
				lista = rimp.pesquisar("data", data.format(new Date()));
				jTableCorrecao.setAutoCreateRowSorter(true);
                                 jTableCorrecao.setModel(new TableModelRetiradas((ArrayList<Retiradas>) lista));
			} catch (RetiradasException e) {
				JOptionPane.showMessageDialog(null, e.getMessage(), 
                "ERRO", JOptionPane.ERROR_MESSAGE);
			}
    }
    
    private void consultaDespesas(){
        DespesasImp dimp = new DespesasImp();
            SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
            ArrayList<Despesas> lista;
            try {
                lista = dimp.pesquisar("data", data.format(new Date()));
                jTableCorrecao.setAutoCreateRowSorter(true);
                jTableCorrecao.setModel(new TableModelDespesas((ArrayList<Despesas>) lista));
            } catch (DespesasException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), 
                "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        
    }
    
    private void consultaPDV(){
        PrincipalImp pimp = new PrincipalImp();
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        ArrayList<Principal> lista;
        try {
            lista = pimp.pesquisar("data", data.format(new Date()));
            jTableCorrecao.setAutoCreateRowSorter(true);
            jTableCorrecao.setModel(new TableModelPrincipal((ArrayList<Principal>)lista));
            
        } catch (PrincipalException e ) {
            JOptionPane.showMessageDialog(null, e.getMessage(), 
                "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
   public static jTela_Correcao getInstance(){
       if (instance == null) {
           instance = new jTela_Correcao();
       }
       return instance;
   }
            
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCorrecao;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDespesas;
    private javax.swing.JRadioButton jRadioButtonPDV;
    private javax.swing.JRadioButton jRadioButtonRetiradas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorrecao;
    // End of variables declaration//GEN-END:variables
}
