/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;

import br.com.marcio.padaria.front.funcoes.TeclasPermitidas;
import br.com.marcio.padaria.model.Principal;
import br.com.marcio.padaria.model.Retiradas;
import br.com.marcio.padaria.repositorio.Imp.PrincipalImp;
import br.com.marcio.padaria.repositorio.Imp.RetiradasImp;
import br.com.marcio.padaria.repositorio.model.Exception.PrincipalException;
import br.com.marcio.padaria.repositorio.model.Exception.RetiradasException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Marcio
 */
public class jTela_Retiradas extends javax.swing.JDialog {

    /**
     * Creates new form jTela_Retiradas
     */
    private static jTela_Retiradas instance = null;
    public jTela_Retiradas() {
        initComponents();
        setAcessibilidade();
        jTextFieldValorRetirada.setDocument(new TeclasPermitidas());
        saldoCaixa();
        somaRetiradas();
    }
    
        SimpleDateFormat dataFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataHoje = dataFormat.format(new Date());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorRetirada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTotalRetirado = new javax.swing.JTextField();
        jTextFieldSaldoCaixa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retiradas");
        setMaximumSize(new java.awt.Dimension(309, 153));
        setMinimumSize(new java.awt.Dimension(309, 153));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor da retirada"));

        jLabel1.setText("Valor a retirar:");

        jTextFieldValorRetirada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldValorRetirada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setMnemonic('e');
        jButton1.setText("Efetuar retirada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorRetirada)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação do caixa"));

        jLabel2.setText("Saldo atual do caixa:");

        jLabel3.setText("Total retirado:");

        jTextFieldTotalRetirado.setText("0.00");
        jTextFieldTotalRetirado.setEnabled(false);

        jTextFieldSaldoCaixa.setText("0.00");
        jTextFieldSaldoCaixa.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jTextFieldSaldoCaixa)
                    .addComponent(jTextFieldTotalRetirado))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaldoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTotalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double totalRetirado = Double.parseDouble(jTextFieldTotalRetirado.getText());
        Double saldoTotalCaixa = Double.parseDouble(jTextFieldSaldoCaixa.getText());
        Double valorRetirado = Double.parseDouble((jTextFieldValorRetirada.getText()).replace(",", "."));
       
        
        if (!(valorRetirado > (saldoTotalCaixa - totalRetirado))){
           Retiradas retirada = new Retiradas();
           RetiradasImp rimp = new RetiradasImp();
           retirada.setData(dataHoje);
           retirada.setValor(valorRetirado.toString());
            try {
                rimp.validaRetirada(retirada);
                rimp.inserir(retirada);
                JOptionPane.showMessageDialog(null, "Valor retirado!",
                       "Informativo", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldValorRetirada.setText("");
                somaRetiradas();
             
             } catch (RetiradasException ex) {
               JOptionPane.showMessageDialog(null, "Não foi possível efetuar esta retirada, contate o Administrador do sistema!",
                       "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Saldo indisponível para esta retirada!","Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Retiradas.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_Retiradas().setVisible(true);
            }
        });
    }
    ArrayList<?> sumList;
    private void saldoCaixa(){
            Principal principal;
            PrincipalImp pimp = new PrincipalImp();
            
           jTextFieldSaldoCaixa.setText("0.00");
        try {
            sumList = pimp.somarValor(dataHoje, dataHoje);
            principal = (Principal) sumList.remove(0);
            if (!principal.isNullValor()){
               //32 bits
               //jTextFieldSaldoCaixa.setText(String.format("%.2f", principal.getValor())); 
               
                //64 bits
                jTextFieldSaldoCaixa.setText(principal.getValor()); 
            } 
        } catch (PrincipalException ex) {
            Logger.getLogger(jTela_Retiradas.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
      }
    private void somaRetiradas(){
            Retiradas retirada;
            RetiradasImp rimp = new RetiradasImp();
            
                jTextFieldTotalRetirado.setText("0.00");
        try {
            sumList = rimp.somarValor(dataHoje, dataHoje);
            retirada = (Retiradas) sumList.remove(0);
            if(!retirada.isNullValor()){
             //jTextFieldTotalRetirado.setText(String.format("%.2f", retirada.getValor()));
             jTextFieldTotalRetirado.setText(String.format(retirada.getValor())); 
            }
        } catch (RetiradasException ex) {
            Logger.getLogger(jTela_Retiradas.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    /*Função de acessibilidade*/
     private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
     
     public static jTela_Retiradas getInstance(){
         if (instance == null) {
             instance = new jTela_Retiradas();
         }
         return instance;
     }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldSaldoCaixa;
    private javax.swing.JTextField jTextFieldTotalRetirado;
    private javax.swing.JTextField jTextFieldValorRetirada;
    // End of variables declaration//GEN-END:variables
}
