/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;
import br.com.marcio.padaria.acesso.publico.imp.GetsPublicoImp;
import br.com.marcio.padaria.front.funcoes.TeclasPermitidas;
import br.com.marcio.padaria.model.Caixa;
import br.com.marcio.padaria.repositorio.Imp.CaixaImp;
import br.com.marcio.padaria.repositorio.model.Exception.CaixaException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;





/**
 *
 * @author Marcio
 */
public class jTela_AbrirCaixa extends javax.swing.JDialog {

    /**
     * Creates new form jTela_AbrirCaixa
     */
   
    GetsPublicoImp getPub;
    private static jTela_AbrirCaixa instance = null;
    
    
    
    public jTela_AbrirCaixa() {
        setAcessibilidade();
        initComponents();
        jTextValor.setDocument(new TeclasPermitidas());
    }
        CaixaImp cimp = new CaixaImp();
        Caixa caixa = new Caixa();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDataAuto = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextObservacao = new javax.swing.JTextArea();
        jButtonSair = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jRadioButtonDataAuto = new javax.swing.JRadioButton();
        jRadioButtonDataManu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa Inicial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(332, 269));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTextValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 74, -1));

        jTextObservacao.setColumns(20);
        jTextObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 312, 59));

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 240, 73, -1));

        jButtonAdicionar.setMnemonic('a');
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 240, -1, -1));

        buttonGroupDataAuto.add(jRadioButtonDataAuto);
        jRadioButtonDataAuto.setSelected(true);
        jRadioButtonDataAuto.setText("Data Automática");
        jRadioButtonDataAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataAutoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonDataAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        buttonGroupDataAuto.add(jRadioButtonDataManu);
        jRadioButtonDataManu.setText("Data Manual");
        jRadioButtonDataManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataManuActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonDataManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jLabel2.setText("Observação:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jCalendar.setDate(new Date());
        jCalendar.setEnabled(false);
        jCalendar.setMinSelectableDate(new Date());
        jCalendar.setWeekOfYearVisible(false);
        getContentPane().add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        setSize(new java.awt.Dimension(348, 313));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
             if (JOptionPane.showConfirmDialog(null, "Deseja adicionar o valor de troco ao caixa?"
                     + "\nCaso ja tenha efetuado esta operação hoje o valor de troco será alterado. "
                     + "\nCaso tenha encerrado o caixa, o valor não será salvo","Atenção", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                abrirCaixar();
            }     
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jRadioButtonDataAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataAutoActionPerformed
        // TODO add your handling code here:
        jCalendar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonDataAutoActionPerformed

    private void jRadioButtonDataManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataManuActionPerformed
        // TODO add your handling code here:
        jCalendar.setEnabled(true);
        jCalendar.setMinSelectableDate(new Date());
    }//GEN-LAST:event_jRadioButtonDataManuActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws javax.swing.UnsupportedLookAndFeelException
     * @throws java.lang.IllegalAccessException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
       try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_AbrirCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_AbrirCaixa().setVisible(true);
            }
        });
    }
    
    private void abrirCaixar(){
                /*  todo - Verificar Insert Identity */ 
        SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");
        String data = null;
        if (jRadioButtonDataAuto.isSelected()) {
            data = format1.format(new Date());
        } else if (jRadioButtonDataManu.isSelected()){
            data = format1.format(jCalendar.getDate());
        }
        
             
               
        caixa.setData(data);
        caixa.setValor("0");
        caixa.setObservacao(jTextObservacao.getText());
        caixa.setTroco(jTextValor.getText().replace(",", "."));
        caixa.setCaixa_ativo("S");
       

       
        try {
              cimp.validaCaixa(caixa);
              cimp.insereAtualiza(caixa);
              jTextValor.setText("");
              JOptionPane.showMessageDialog(null,"O valor de troco foi atualizado!",
                                "Informativo", JOptionPane.INFORMATION_MESSAGE);
              this.dispose();
            
        } catch (CaixaException e) {
          JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    
    private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
    
    public static jTela_AbrirCaixa getInstance(){
        if (instance == null) {
            instance = new jTela_AbrirCaixa();
        }
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDataAuto;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonSair;
    private com.toedter.calendar.JCalendar jCalendar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonDataAuto;
    private javax.swing.JRadioButton jRadioButtonDataManu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextObservacao;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
