

package br.com.marcio.padaria.front;

import br.com.marcio.padaria.front.funcoes.TableModelCaixa;
import br.com.marcio.padaria.front.funcoes.TableModelClientePendencia;
import br.com.marcio.padaria.front.funcoes.TableModelDespesas;
import br.com.marcio.padaria.front.funcoes.TableModelPrincipal;
import br.com.marcio.padaria.front.funcoes.TableModelRetiradas;
import br.com.marcio.padaria.model.Caixa;
import br.com.marcio.padaria.model.ClientePendencia;
import br.com.marcio.padaria.model.Despesas;
import br.com.marcio.padaria.model.Principal;
import br.com.marcio.padaria.model.Retiradas;
import br.com.marcio.padaria.repositorio.Imp.CaixaImp;
import br.com.marcio.padaria.repositorio.Imp.ClientePendenciaImp;
import br.com.marcio.padaria.repositorio.Imp.DespesasImp;
import br.com.marcio.padaria.repositorio.Imp.PrincipalImp;
import br.com.marcio.padaria.repositorio.Imp.RetiradasImp;
import br.com.marcio.padaria.repositorio.model.Exception.CaixaException;
import br.com.marcio.padaria.repositorio.model.Exception.ClientesException;
import br.com.marcio.padaria.repositorio.model.Exception.DespesasException;
import br.com.marcio.padaria.repositorio.model.Exception.PendenciasException;
import br.com.marcio.padaria.repositorio.model.Exception.PrincipalException;
import br.com.marcio.padaria.repositorio.model.Exception.RetiradasException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author Marcio
 */
public class jTela_Relatorio extends javax.swing.JFrame {
    //TODO Verificar Problema com PDV
     ArrayList<?> lista;
     ArrayList<?> listaPrint;
    private static jTela_Relatorio instance = null;
    private final String caminho_relatorio = "Relatorios/";
   
    
    public jTela_Relatorio() {
        initComponents();
        setAcessibilidade();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateInicio = new com.toedter.calendar.JDateChooser();
        jDateFim = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox();
        jButtonPrint = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelSomaTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableResultado);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButtonPesquisar.setMnemonic('p');
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Relatório de:");

        jDateInicio.setDate(new Date());
        jDateInicio.setMaxSelectableDate(new Date());

        jDateFim.setDate(new Date());
        jDateFim.setMaxSelectableDate(new Date());
        jDateFim.setMinSelectableDate(null);

        jLabel2.setText("Início:");

        jLabel3.setText("Fim:");

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PDV", "Caixa", "Despesas", "Retiradas", "Pendências" }));

        jButtonPrint.setMnemonic('i');
        jButtonPrint.setText("Imprimir");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateFim, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrint)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel4.setText("Total:");

        jLabelSomaTotal.setText("0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSomaTotal)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelSomaTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        	String dataInicio = new 
        SimpleDateFormat("dd/MM/yyyy").format(jDateInicio.getDate());
                String dataFim = new 
        SimpleDateFormat("dd/MM/yyyy").format(jDateFim.getDate());       
                             
                
                switch ((String)jComboBoxFiltro.getSelectedItem()){
                    case "Caixa" :
                        CaixaImp cimp = new CaixaImp();
                        Caixa caixa;
                    try {
                         lista = cimp.pesquisar("data",dataInicio, dataFim); 
                         listaPrint = lista;
                         
                         jTableResultado.setAutoCreateRowSorter(true);
                        jTableResultado.setModel(new TableModelCaixa((ArrayList<Caixa>) lista));
                        lista = cimp.somarValor(dataInicio, dataFim);
                        caixa = (Caixa) lista.remove(0);
                        jLabelSomaTotal.setText(caixa.getValor());
                    } catch (CaixaException e) {	
                    }
                     break;
                        
                        case "PDV" :
                        PrincipalImp pimp = new PrincipalImp();
                        Principal principal;
                    try {
                        lista = pimp.pesquisar("data",dataInicio, dataFim);
                        listaPrint = lista;
                        
                        jTableResultado.setAutoCreateRowSorter(true);
                        jTableResultado.setModel(new TableModelPrincipal((ArrayList<Principal>) lista));
                        
                        lista = pimp.somarValor(dataInicio, dataFim);
                        principal = (Principal) lista.remove(0);
                        jLabelSomaTotal.setText(principal.getValor());
                        
                        
                    } catch (PrincipalException e) {	
                    }
                     break;
                            
                            case "Pendências" :
                        ClientePendenciaImp cdimp = new ClientePendenciaImp();
                        ClientePendencia clientePendencia;
                    try {
                        lista = cdimp.pesquisar(dataInicio, dataFim);
                        listaPrint = lista;
                        jTableResultado.setAutoCreateRowSorter(true);
                        jTableResultado.setModel(new TableModelClientePendencia((ArrayList<ClientePendencia>) lista));	
                        lista = cdimp.somarValor(dataInicio, dataFim);
                        clientePendencia = (ClientePendencia) lista.remove(0);
                        jLabelSomaTotal.setText(clientePendencia.getValor());
                   	
                    } catch (ClientesException | PendenciasException e) {
                 
                }
                     break;
                                
                            case "Despesas" :
                        DespesasImp dimp = new DespesasImp();
                        Despesas despesa;
                    try {
                        lista = dimp.pesquisar("data", dataInicio, dataFim);
                        listaPrint = lista;
                        jTableResultado.setAutoCreateRowSorter(true);
                        jTableResultado.setModel(new TableModelDespesas((ArrayList<Despesas>) lista));	
                   	lista = dimp.somarValor(dataInicio, dataFim);
                        despesa = (Despesas) lista.remove(0);
                        jLabelSomaTotal.setText(despesa.getValor());
                        
                    } catch (DespesasException e) {
                 
                }
                     break;
                                
                         case "Retiradas" :
                        RetiradasImp rimp = new RetiradasImp();
                        Retiradas retirada;
                    try {
                        lista = rimp.pesquisar("data", dataInicio, dataFim);
                        listaPrint = lista;
                        jTableResultado.setAutoCreateRowSorter(true);
                        jTableResultado.setModel(new TableModelRetiradas((ArrayList<Retiradas>) lista));	
                   	lista = rimp.somarValor(dataInicio, dataFim);
                        retirada = (Retiradas) lista.remove(0);
                        jLabelSomaTotal.setText(retirada.getValor());
                    } catch (RetiradasException e) {
                 
                }
                     break;
                 
                }
               

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
                JasperReport report = null;
           
         try {
             
            
                     switch ((String)jComboBoxFiltro.getSelectedItem()) {
                         case "Caixa" :
                                 report = JasperCompileManager
                     .compileReport(caminho_relatorio + "caixaReport.jrxml");
                         break;
                             
                         case "Despesas" :
                             report = JasperCompileManager
                     .compileReport(caminho_relatorio + "despesasReport.jrxml");
                         break;
                             
                         case "Pendências" :
                             report = JasperCompileManager
                     .compileReport(caminho_relatorio + "pendenciasReport.jrxml");
                         break;
                             
                         case "PDV" :
                             report = JasperCompileManager
                     .compileReport(caminho_relatorio + "principalReport.jrxml");
                         break;
                             
                         case "Retiradas" :
                             report = JasperCompileManager
                     .compileReport(caminho_relatorio + "retiradasReport.jrxml");
                         break;                               
                         
                     }
                     
             JasperPrint print = JasperFillManager.fillReport(report, null,
				new JRBeanCollectionDataSource(listaPrint));

		JasperViewer.viewReport(print, false); 
                
         } catch (JRException e) {
             //Logger.getLogger(jTela_Relatorio.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,e.getMessage());
         }
		       
    }//GEN-LAST:event_jButtonPrintActionPerformed


    public static void main(String args[]){
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      
        //</editor-fold>

        Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_Relatorio().setVisible(true);
            }
        });
    }
    
    /*Função de acessibilidade*/
     private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
     
     public static jTela_Relatorio getInstance(){
         if (instance == null) {
             instance = new jTela_Relatorio();
         }
         return instance;
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxFiltro;
    private com.toedter.calendar.JDateChooser jDateFim;
    private com.toedter.calendar.JDateChooser jDateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSomaTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultado;
    // End of variables declaration//GEN-END:variables
}
