/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.marcio.padaria.front;


import br.com.marcio.padaria.front.funcoes.TableModelDespesas;
import br.com.marcio.padaria.front.funcoes.TeclasPermitidas;
import br.com.marcio.padaria.model.Caixa;
import br.com.marcio.padaria.model.Despesas;
import br.com.marcio.padaria.repositorio.Imp.DespesasImp;
import br.com.marcio.padaria.repositorio.model.Exception.DespesasException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Marcio
 */
public class jTela_Despesas extends javax.swing.JDialog {
    String hoje = new         
    SimpleDateFormat("dd/MM/yyyy").format(new Date());
    private static jTela_Despesas instance = null;
    /**
     * Creates new form jTela_Despesas
     */
    public jTela_Despesas() {
        initComponents();
        jTextFieldValorNota.setDocument(new TeclasPermitidas());
        CarregaDados();
        setAcessibilidade();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupData = new javax.swing.ButtonGroup();
        jPanelAdicionarDespesa = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jTextFieldDescricaoNota = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDespesas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorNota = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jTextFieldTotalDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");
        setMaximumSize(new java.awt.Dimension(502, 291));
        setMinimumSize(new java.awt.Dimension(502, 291));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanelAdicionarDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar despesa"));

        jButtonSalvar.setMnemonic('s');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAdicionar.setMnemonic('a');
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jTextFieldDescricaoNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDescricaoNota.setEnabled(false);

        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDespesas);

        jLabel2.setText("Descrição:");

        jLabel1.setText("Valor da nota:");

        jTextFieldValorNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldValorNota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValorNota.setEnabled(false);
        jTextFieldValorNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdicionarDespesaLayout = new javax.swing.GroupLayout(jPanelAdicionarDespesa);
        jPanelAdicionarDespesa.setLayout(jPanelAdicionarDespesaLayout);
        jPanelAdicionarDespesaLayout.setHorizontalGroup(
            jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionarDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdicionarDespesaLayout.createSequentialGroup()
                        .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorNota)
                            .addComponent(jLabel1)
                            .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescricaoNota)
                            .addGroup(jPanelAdicionarDespesaLayout.createSequentialGroup()
                                .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanelAdicionarDespesaLayout.createSequentialGroup()
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdicionarDespesaLayout.setVerticalGroup(
            jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionarDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescricaoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTextFieldTotalDespesa.setEditable(false);
        jTextFieldTotalDespesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTotalDespesa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Total:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTotalDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        AdicionarItem();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        VoltarPadrao();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
     
       Caixa caixa = new Caixa();
       caixa.setValor(jTextFieldValorNota.getText().toString());
     
        Despesas despesa = new Despesas();
        DespesasImp dimp = new DespesasImp();
        
        despesa.setData(hoje);
        despesa.setDescricao(jTextFieldDescricaoNota.getText());
        despesa.setValor(jTextFieldValorNota.getText().replace(",", "."));
      
      try {        
        dimp.validaDespesa(despesa);
        dimp.inserir(despesa);
       
    } catch (DespesasException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(), 
                "ERRO", JOptionPane.ERROR_MESSAGE);
    }
       CarregaDados();
        VoltarPadrao();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldValorNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorNotaActionPerformed

    }//GEN-LAST:event_jTextFieldValorNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jTela_Despesas.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jTela_Despesas().setVisible(true);
            }
        });
    }

    private void AdicionarItem(){
        jButtonAdicionar.setEnabled(false);
 
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldValorNota.setEnabled(true);
        jTextFieldDescricaoNota.setEnabled(true);
        
        jTableDespesas.setEnabled(false);
       
        
    }
       
    private void VoltarPadrao(){
        jButtonAdicionar.setEnabled(true);
   
        
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
        jTextFieldValorNota.setEnabled(false);
        jTextFieldDescricaoNota.setEnabled(false);
        
        jTableDespesas.setEnabled(true);
       
        jTextFieldDescricaoNota.setText("");
        jTextFieldValorNota.setText("");
        
    }
    
    private void CarregaDados(){
        
    
        ArrayList<Despesas> lista;
        DespesasImp dimp = new DespesasImp();
        Despesas despesa;
                    try {
                        lista = dimp.pesquisar("data", hoje, hoje);    
                        jTableDespesas.setAutoCreateRowSorter(true);
                        jTableDespesas.setModel(new TableModelDespesas((ArrayList<Despesas>) lista));	
                   	lista = dimp.somarValor(hoje, hoje);
                        despesa = (Despesas) lista.remove(0);
                        jTextFieldTotalDespesa.setText(despesa.getValor());
         }
                       catch (DespesasException e) {
                           JOptionPane.showMessageDialog(null, e.getMessage());
                }
                    
    }
    
     /*Função de acessibilidade*/
     private void setAcessibilidade() {
        JRootPane meuJPanel = getRootPane();
        meuJPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meuJPanel.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
       });
    } 
     
     
     public static jTela_Despesas getInstance() {
      if (instance == null)
         instance = new jTela_Despesas();
      return instance;
   }
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupData;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAdicionarDespesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDespesas;
    private javax.swing.JTextField jTextFieldDescricaoNota;
    private javax.swing.JTextField jTextFieldTotalDespesa;
    private javax.swing.JTextField jTextFieldValorNota;
    // End of variables declaration//GEN-END:variables
}
